config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
      resources :categories, only: [:index, :show]
      resources :audios, only: [:index, :show] do
        collection do
          get :top
          get :favorite
        end
      end
      resources :likes, only: [:create]
      delete "likes", to: "likes#destroy"
      resources :users, only: [] do
        collection do
          get :profile
        end
      end
    end
  end

  namespace :admin do
    root "dashboard#index"
    resources :dashboard, only: [:index]
    resources :users, except: [:new]
    resources :categories
    resources :audios
    resources :settings, only: [:index, :create]
    resources :transactions, except: [:edit, :update, :destroy]
    resources :activities, only: [:index]
  end

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  acts_as_paranoid
  mount_uploader :uploaded_file, AudioUploader
  include CustomThumbnailJson

  has_many :listens
  has_many :likes
  belongs_to :category
  after_destroy :destroy_activities

  delegate :thumbnail, to: :category

  validates_presence_of :name, :description, :category_id, :uploaded_file

  enum status: [:draft, :approved]

  scope :top, -> { Audio.approved.order("listens_count desc") }

  def activities
    listen_ids = listens.ids
    like_ids = likes.ids
    Activity.listens.where(subject_id: listen_ids).or(Activity.likes.where(subject_id: like_ids))
  end

  def uploaded_file_extension
    uploaded_file.file.extension.downcase if uploaded_file && uploaded_file.file
  end

  def uploaded_file_name
    uploaded_file.file.filename if uploaded_file && uploaded_file.file
  end

  def uploaded_file_url
    case uploaded_file_extension
    when 'mp3'
      "#{ENV['AWS_CLOUDFRONT_URL_STREAMING']}/cfx/st/mp3:#{uploaded_file.path[0..-5]}"
    when 'm4a'
      "#{ENV['AWS_CLOUDFRONT_URL_STREAMING']}/cfx/st/mp4:#{uploaded_file.path}"
    end
  end

  private

  def destroy_activities
    activities.destroy_all
  end
end

app/controllers/admin/audios_controller.rb
class Admin::AudiosController < Admin::ApplicationController
  before_action :set_audio, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category_id].present?
      @category = Category.find params[:category_id]
      @audios = @category.audios.page(params[:page]).per(Setting.admin_per_page)
    else
      @audios = Audio.includes(:category).page(params[:page]).per(Setting.admin_per_page)
    end
  end

  def show
    gon.uploaded_file_url = @audio.uploaded_file_url
  end

  def new
    @audio = Audio.new
  end

  def edit
  end

  def create
    @audio = Audio.new(audio_params)
    respond_to do |format|
      if @audio.save
        format.html { redirect_to admin_audio_url(@audio), notice: 'Audio was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @audio.update(audio_params)
        format.html { redirect_to admin_audio_url(@audio), notice: 'Audio was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    @audio.destroy
    respond_to do |format|
      format.html { redirect_to admin_audios_url, notice: 'Audio was successfully destroyed.' }
    end
  end

  private
    def set_audio
      @audio = Audio.find(params[:id])
    end

    def audio_params
      params[:audio]['name'] = 'Audio name' if params[:audio]['name'].blank?
      params[:audio]['description'] = 'Audio description' if params[:audio]['description'].blank?
      params[:audio]['category_id'] = Category.normal.order(:name).last.id if params[:audio]['category_id'].blank?
      params.require(:audio).permit(:name, :description, :uploaded_file, :uploaded_file_cache, :category_id, :status)
    end
end

app/controllers/api/audios_controller.rb
class Api::AudiosController < Api::ApplicationController
  def index
    @audios = Audio.approved.includes(:category)
  end

  def show
    @audio = Audio.approved.find params[:id]
    @listen = current_user.listens.create! audio: @audio
  end

  def top
    @audios = Audio.includes(:category).top.limit(Setting.top_audio_quantity)
  end

  def favorite
    @audios = current_user.favorite_audios.includes(:category).order(created_at: :desc)
  end
end

app/views/admin/audios/_form.html.erb
<%= form_for [:admin, @audio], html: { multipart: true, id: "fileupload" } do |f| %>
  <div class="row">
    <div class="col-md-9">
      <div class="box box-solid">
        <div class="box-header"></div>
        <div class="box-body pad">
          <%= render "admin/shared/form_error", record: @audio %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control", required: true %>
          </div>
          <% if @audio.uploaded_file? %>
            <div class="form-group">
              <%= f.label :uploaded_file_url, "Audio" %>
              <br>
              <%= link_to @audio.uploaded_file_url, @audio.uploaded_file_url, id: "audio_uploaded_file_url" %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_field :description, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <%= f.label :category_id %>
            <select class="form-control" name="audio[category_id]" id="dropdown" required="true">
              <option></option>
              <% Category.walk_tree do |category, level| %>
                <% if category.id == @audio.category_id || category.id.to_s == params[:category_id] %>
                  <option selected="selected" value="<%= category.id %>"><%= "#{'-'*level}#{category.path_name}" %></option>
                <% else %>
                  <option value="<%= category.id %>"><%= "#{'-'*level} #{category.path_name}" %></option>
                <% end %>
              <% end %>
            </select>
          </div>
          <div class="form-group">
            <%= f.label :uploaded_file, "Upload" %>
            <br>
            <div class='btn btn-primary fileinput-button'>
              <i class='glyphicon glyphicon-plus'></i>
              Select a file
              <%= f.file_field :uploaded_file, accept: "audio/*" %>
              <%= f.hidden_field :uploaded_file_cache %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="box box-solid">
        <div class="box-header"></div>
        <div class="box-body">
          <% if @audio.persisted? %>
            <div class="form-group">
              <%= f.label :status %>
              <%= f.select :status, options_for_select(Audio.statuses.keys, f.object.status), {}, class: "form-control" %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.submit "Save", class: "btn btn-success btn-block", id: "save_audio" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script id="template-upload" type="text/x-tmpl">
  <div class="row">
    <div class="col-md-9">
      <div class="box box-solid">
        <div class="box-body pad">
          <table class="table">
            <tbody>
              <tr class="template-upload">
                <td width="45%">
                  <p class="name"><h3>{%=o.name%}</h3></p>
                  <p class="size">Processing...</p>
                  <strong class="error text-danger"></strong>
                </td>
                <td width="45%" style="vertical-align: middle;">
                  <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                  </div>
                  <p><h1 id="js-completed" align="center"></h1></p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</script>

app/views/admin/audios/_player.html.erb
<script src="https://jwpsrv.com/library/4+R8PsscEeO69iIACooLPQ.js"></script>
<div id="my-player"></div>

app/views/admin/audios/create.js.erb
<% if @audio.new_record? %>
  $(".size").text("Failed")
<% else %>
  $("#fileupload").attr('action', "<%= admin_audio_path(@audio) %>")
  $("#fileupload").append('<input type="hidden" name="_method" value="patch">')
  $(".size").text("Uploaded")
  $("#save_audio").removeAttr('disabled')
<% end %>

app/views/admin/audios/edit.html.erb
<%= content_for :title, "Edit #{@audio.name}" %>

<%= link_to "Back", :back, class: "btn btn-default" %>
<%= link_to "Show", admin_audio_path(@audio), class: "btn btn-primary" %>

<%= render "form" %>

app/views/admin/audios/index.html.erb
<%= content_for :title, "Audios" %>

<%= link_to "Add a new audio", new_admin_audio_path(category_id: params[:category_id]), class: "btn btn-success" %>

<div class="box box-solid">
  <div class="box-header">
    <h3 class="box-title"></h3>
    <% if @category %>
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li>
            <%= link_to @category.name, admin_category_path(@category) %>
          </li>
          <li class="active">
            <%= link_to admin_audios_path(category_id: @category.id) do %>
              Audios
              <small class="badge pull-right bg-yellow">
                <%= @category.audios.count %>
              </small>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Category</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @audios.each do |audio| %>
          <tr>
            <td><%= link_to audio.name, admin_audio_path(audio) %></td>
            <td><%= link_to audio.category.name, admin_category_path(audio.category) %></td>
            <td><%= audio.status %></td>
            <td>
              <%= link_to 'Show', admin_audio_path(audio), class: 'btn btn-default btn-sm' %>
              <%= link_to 'Edit', edit_admin_audio_path(audio), class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Delete', admin_audio_path(audio), class: 'btn btn-danger btn-sm', :method => :delete, :data => { :confirm => 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= paginate @audios %>

app/views/admin/audios/new.html.erb
<%= content_for :title, "New Audio" %>

<%= link_to "Back", :back, class: "btn btn-default" %>

<%= render "form" %>

app/views/admin/audios/show.html.erb
<%= content_for :title, @audio.name %>

<%= link_to 'Back', :back, class: 'btn btn-default' %>
<%= link_to 'Edit', edit_admin_audio_path(@audio), class: 'btn btn-primary' %>
<%= link_to 'Delete', admin_audio_path(@audio), class: 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' } %>

<div class="box box-solid">
  <div class="box-header">
    <h3 class="box-title">Detail</h3>
  </div>
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <td><b>Name</b></td>
        <td>
          <%= @audio.name %>
        </td>
      </tr>
      <tr>
        <td><b>Uploaded file name</b></td>
        <td>
          <%= @audio.uploaded_file_name %>
        </td>
      </tr>
      <tr>
        <td><b>Audio</b></td>
        <td>
          <%= render "player" %>
        </td>
      </tr>
      <tr>
        <td><b>Description</b></td>
        <td>
          <%= @audio.description %>
        </td>
      </tr>
      <tr>
        <td><b>Category</b></td>
        <td>
          <%= link_to @audio.category.name, admin_category_path(@audio.category) %>
        </td>
      </tr>
      <tr>
        <td><b>Status</b></td>
        <td>
          <%= @audio.status %>
        </td>
      </tr>
      <tr>
        <td><b>Created at</b></td>
        <td>
          <%= @audio.created_at %>
        </td>
      </tr>
      <tr>
        <td><b>Updated at</b></td>
        <td>
          <%= @audio.updated_at %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/admin/audios/update.js.erb
<% if @audio.new_record? %>
  $(".size").text("Failed")
<% else %>
  $("#audio_uploaded_file_url").text("<%= @audio.uploaded_file_url %>")
  $("#audio_uploaded_file_url").attr('href', "<%= @audio.uploaded_file_url %>")
  $(".size").text("Uploaded")
  $("#save_audio").removeAttr('disabled')
<% end %>