config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
      resources :categories, only: [:index, :show]
      resources :audios, only: [:index, :show] do
        collection do
          get :top
          get :favorite
        end
      end
      resources :likes, only: [:create]
      delete "likes", to: "likes#destroy"
      resources :users, only: [] do
        collection do
          get :profile
        end
      end
    end
  end

  namespace :admin do
    root "dashboard#index"
    resources :dashboard, only: [:index]
    resources :users, except: [:new]
    resources :categories
    resources :audios
    resources :settings, only: [:index, :create]
    resources :transactions, except: [:edit, :update, :destroy]
    resources :activities, only: [:index]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  mount_uploader :thumbnail, ThumbnailUploader
  extend ActsAsTree::TreeWalker
  extend ActsAsTree::TreeView

  acts_as_tree order: "name"
  acts_as_paranoid

  validates :name, presence: true, uniqueness: true

  has_many :audios, dependent: :destroy

  scope :limited_access, -> { where(limited_access: true) }
  scope :normal, -> { where(limited_access: false) }

  def path_name
    if root?
      name
    else
      category = self
      names = [name]
      while category.parent do
        names << category.parent.name
        category = category.parent
      end
      names.reverse.join(" . ")
    end
  end

  def approved_audios
    audios.approved
  end

  def thumbnails
    {
      original: { url: thumbnail.url },
      medium: { url: thumbnail.url(:medium) },
      small: { url: thumbnail.url(:small) },
      smaller: { url: thumbnail.url(:smaller) }
    }
  end

  def as_json(options = nil)
    {
      id: id,
      name: name,
      description: description,
      limited_access: limited_access,
      created_at: created_at,
      updated_at: updated_at,
      parent_id: parent_id,
      thumbnails: thumbnails,
      audios: approved_audios,
      children: children
    }
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_url(@category), notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_url(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :limited_access, :thumbnail, :thumbnail_cache, :parent_id)
    end
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < Api::ApplicationController
  def index
    if current_user.admin?
      @categories = Category.roots
    else
      @categories = Category.roots.normal
    end
  end

  def show
    if current_user.admin?
      @category = Category.find params[:id]
    else
      @category = Category.normal.find params[:id]
    end
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <div class="row">
    <div class="col-md-9">
      <div class="box box-solid">
        <div class="box-header">
          <div class="box-body pad">
            <%= render "admin/shared/form_error", record: @category %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_field :description, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :thumbnail %>
              <%= image_tag(@category.thumbnail_url(:medium)) %>
              <%= f.file_field :thumbnail, class: "form-control", accept: "image/*" %>
              <%= f.hidden_field :thumbnail_cache %>
            </div>
            <div class="form-group">
              <%= f.label :parent_id %>
              <select class="form-control" name="category[parent_id]" id="dropdown">
                <option></option>
                <% Category.walk_tree do |category, level| %>
                  <% if category.id == @category.parent_id || category.id.to_s == params[:category_id] %>
                    <option selected="selected" value="<%= category.id %>"><%= "#{'-'*level} #{category.path_name}" %></option>
                  <% else %>
                    <option value="<%= category.id %>"><%= "#{'-'*level} #{category.path_name}" %></option>
                  <% end %>
                <% end %>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="box box-solid">
        <div class="box-header"></div>
        <div class="box-body">
          <div class="form-group">
            <%= f.label :limited_access %>
            <%= f.check_box :limited_access %>
          </div>
          <div class="form-group">
            <%= f.submit class: "btn btn-success btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<%= content_for :title, "Edit #{@category.name}" %>

<%= link_to "Back", :back, class: "btn btn-default" %>
<%= link_to "Show", admin_category_path(@category), class: "btn btn-primary" %>

<%= render "form" %>

app/views/admin/categories/index.html.erb
<%= content_for :title, "Categories" %>

<%= link_to "Add a new category", new_admin_category_path, class: "btn btn-success" %>

<div class="box box-solid">
  <div class="box-header">
    <h3 class="box-title"></h3>
  </div>
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th style="width:40%;">Name</th>
          <th>Audios</th>
          <th>Limited access</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% Category.walk_tree do |category, level| %>
          <tr>
            <td>
              <%= link_to admin_category_path(category) do %>
                <%= "#{'-'*level} " %>
                <i class="fa fa-folder-open"></i>
                <%= category.name %>
              <% end %>
            </td>
            <td><%= category.audios.count %></td>
            <td><%= category.limited_access %></td>
            <td>
              <%= link_to 'Show', admin_category_path(category), class: 'btn btn-default btn-sm' %>
              <%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Delete', admin_category_path(category), class: 'btn btn-danger btn-sm', :method => :delete, :data => { :confirm => 'Are you sure? All sub categories and audios inside this category will be deleted, too!' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/categories/show.html.erb
<%= content_for :title, @category.name %>

<%= link_to 'Back', :back, class: 'btn btn-default' %>
<%= link_to 'Edit', edit_admin_category_path(@category), class: 'btn btn-primary' %>
<%= link_to 'Delete', admin_category_path(@category), class: 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure? All sub categories and audios inside this category will be deleted, too!' } %>

<div class="box box-solid">
  <div class="box-header">
    <h3 class="box-title"></h3>
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active">
          <%= link_to @category.name, admin_category_path(@category) %>
        </li>
        <li>
          <%= link_to admin_audios_path(category_id: @category.id) do %>
            Audios
            <small class="badge pull-right bg-yellow">
              <%= @category.audios.count %>
            </small>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <% if @category.parent %>
        <tr>
          <td>
            <%= link_to admin_category_path(@category.parent) do %>
              <i class="fa fa-arrow-left"></i>
              <i class="fa fa-folder-open"></i>
              <%= @category.parent.name %>
            <% end %>
          </td>
          <td>Parent category</td>
        </tr>
      <% else %>
        <tr>
          <td>
            <%= link_to admin_categories_path do %>
              <i class="fa fa-arrow-left"></i>
              All categories
            <% end %>
          </td>
          <td></td>
        </tr>
      <% end %>
      <% @category.walk_tree do |category, level| %>
        <tr>
          <td>
            <%= link_to admin_category_path(category) do %>
              <%= "#{'-'*level} " %>
              <i class="fa fa-folder-open"></i>
              <%= category.name %>
            <% end %>
          </td>
          <td></td>
        </tr>
      <% end %>
      <tr>
        <td>
          <%= link_to new_admin_category_path(category_id: params[:id]) do %>
            <i class="fa fa-folder-open-o"></i>
            New category
          <% end %>
        </td>
        <td></td>
      </tr>
      <tr>
        <td><b>Name</b></td>
        <td>
          <%= @category.name %>
        </td>
      </tr>
      <tr>
        <td><b>Description</b></td>
        <td>
          <%= @category.description %>
        </td>
      </tr>
      <tr>
        <td><b>Limited access</b></td>
        <td>
          <%= @category.limited_access %>
        </td>
      </tr>
      <tr>
        <td><b>Thumbnail</b></td>
        <td>
          <%= image_tag(@category.thumbnail_url(:medium)) %>
        </td>
      </tr>
      <tr>
        <td><b>Created at</b></td>
        <td>
          <%= @category.created_at %>
        </td>
      </tr>
      <tr>
        <td><b>Updated at</b></td>
        <td>
          <%= @category.updated_at %>
        </td>
      </tr>
    </table>
  </div>
</div>