config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
      resources :categories, only: [:index, :show]
      resources :audios, only: [:index, :show] do
        collection do
          get :top
          get :favorite
        end
      end
      resources :likes, only: [:create]
      delete "likes", to: "likes#destroy"
      resources :users, only: [] do
        collection do
          get :profile
        end
      end
    end
  end

  namespace :admin do
    root "dashboard#index"
    resources :dashboard, only: [:index]
    resources :users, except: [:new]
    resources :categories
    resources :audios
    resources :settings, only: [:index, :create]
    resources :transactions, except: [:edit, :update, :destroy]
    resources :activities, only: [:index]
  end

end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::ApplicationController
  before_action :set_transaction, only: [:show]
  before_action :filter_transactions, only: [:index]

  def index
    @transactions = @transactions.includes(:user).order(created_at: :desc).page(params[:page]).per(Setting.admin_per_page)
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to admin_transaction_url(@transaction), notice: 'Transaction was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:user_id, :amount)
    end

    def filter_transactions
      if params[:date_range_filter].present?
        from, to = params[:date_range_filter].split(' - ')
        from = DateTime.strptime(from, Setting.date_format).to_time
        to = DateTime.strptime(to, Setting.date_format).end_of_day.to_time
        @transactions = Transaction.where(created_at: from..to)
      else
        @transactions = Transaction.all
      end
    end
end

app/helpers/transaction_helper.rb
module TransactionHelper
  def money_amount_in_vnd amount
    number_to_currency(amount, unit: "VND")
  end
end

app/views/admin/transactions/_date_filter.html.erb
<div class="box box-solid">
  <div class="box-body">
    <div class="row">
      <div class="col-md-3">
        <%= form_tag admin_transactions_path, method: :get do %>
          <div class="form-group">
            <%= label_tag :date_range_filter, "Date filter" %>
            <%= text_field_tag :date_range_filter, params[:date_range_filter], class: "form-control daterange" %>
          </div>
          <div class="form-group">
            <%= submit_tag "Filter", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/transactions/_form.html.erb
<%= form_for [:admin, @transaction] do |f| %>
  <div class="row">
    <div class="col-md-9">
      <div class="box box-solid">
        <div class="box-header">
          <div class="box-body pad">
            <%= render "admin/shared/form_error", record: @transaction %>
            <div class="form-group">
              <%= f.label :user_id %>
              <%= f.collection_select :user_id, User.normal_user, :id, :email, {}, class: "form-control", id: "dropdown", required: true %>
            </div>
            <div class="form-group">
              <%= f.label :amount %>
              <div class="input-group">
                <%= f.number_field :amount, class: "form-control" %>
                <span class="input-group-addon">VND</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="box box-solid">
        <div class="box-header"></div>
        <div class="box-body">
          <div class="form-group">
            <%= f.submit class: "btn btn-success btn-block", :data => { :confirm => 'Are you sure? Transaction can not be changed after it was created.' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/transactions/index.html.erb
<%= content_for :title, "Transactions" %>

<%= link_to "Add a new transaction", new_admin_transaction_path, class: "btn btn-success" %>

<%= render "date_filter" %>

<div class="box box-solid">
  <div class="box-header">
  </div>
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>User</th>
          <th>Amount</th>
          <th>Created at</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= link_to transaction.id, admin_transaction_path(transaction) %></td>
            <td>
              <% if transaction.user %>
                <%= link_to transaction.user.email, admin_user_path(transaction.user) %>
              <% else %>
                A deleted user
              <% end %>
            </td>
            <td><%= transaction.amount %></td>
            <td><%= transaction.created_at %></td>
            <td>
              <%= link_to 'Show', admin_transaction_path(transaction), class: 'btn btn-default btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= paginate @transactions %>

app/views/admin/transactions/new.html.erb
<%= content_for :title, "New Transaction" %>

<%= link_to "Back", :back, class: "btn btn-default" %>

<%= render "form" %>

app/views/admin/transactions/show.html.erb
<%= content_for :title, "Transaction #{@transaction.id}" %>

<%= link_to 'Back', :back, class: 'btn btn-default' %>

<div class="box box-solid">
  <div class="box-header">
    <h3 class="box-title"></h3>
  </div>
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tr>
        <td><b>ID</b></td>
        <td>
          <%= @transaction.id %>
        </td>
      </tr>
      <tr>
        <td><b>User</b></td>
        <td>
        <% if @transaction.user %>
          <%= link_to @transaction.user.email, admin_user_path(@transaction.user) %>
        <% else %>
          A deleted user
        <% end %>
        </td>
      </tr>
      <tr>
        <td><b>Amount</b></td>
        <td>
          <%= @transaction.amount %>
        </td>
      </tr>
      <tr>
        <td><b>Last modified by</b></td>
        <td>
          <% modifier = @transaction.audits.last.user %>
          <%= link_to modifier.email, admin_user_path(modifier) %>
        </td>
      </tr>
      <tr>
        <td><b>Created at</b></td>
        <td>
          <%= @transaction.created_at %>
        </td>
      </tr>
      <tr>
        <td><b>Updated at</b></td>
        <td>
          <%= @transaction.updated_at %>
        </td>
      </tr>
    </table>
  </div>
</div>