config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
      resources :categories, only: [:index, :show]
      resources :audios, only: [:index, :show] do
        collection do
          get :top
          get :favorite
        end
      end
      resources :likes, only: [:create]
      delete "likes", to: "likes#destroy"
      resources :users, only: [] do
        collection do
          get :profile
        end
      end
    end
  end

  namespace :admin do
    root "dashboard#index"
    resources :dashboard, only: [:index]
    resources :users, except: [:new]
    resources :categories
    resources :audios
    resources :settings, only: [:index, :create]
    resources :transactions, except: [:edit, :update, :destroy]
    resources :activities, only: [:index]
  end

end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="<%= admin_root_path %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>BS</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b><%= Setting.app_name %></b></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <%= image_tag "avatar.png", class: "user-image" %>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user.email %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <%= image_tag "avatar.png", class: "img-circle" %>
              <p>
                <small>Member since <%= current_user.created_at %></small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="<%= edit_user_registration_path %>" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="<%= destroy_user_session_path %>" class="btn btn-default btn-flat" data-method="delete">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "avatar.png", class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.email %></p>
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <!-- search form (Optional) -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..."/>
        <span class="input-group-btn">
          <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Manager</li>
        <!-- Optionally, you can add icons to the links -->
      <% if current_user.admin? %>
        <li class="<%= 'active' if current_page?(admin_root_path) %>"><a href="<%= admin_root_path %>"><i class='fa fa-dashboard'></i> <span>Dashboard</span></a></li>
      <% end %>
      <% if can? :read, User %>
        <li class="<%= 'active' if current_page?(admin_users_path) %>"><a href="<%= admin_users_path %>"><i class='fa fa-users'></i> <span>Users</span></a></li>
      <% end %>
      <% if can? :read, Category %>
        <li class="<%= 'active' if current_page?(admin_categories_path) %>"><a href="<%= admin_categories_path %>"><i class='fa fa-folder-open'></i> <span>Categories</span></a></li>
      <% end %>
      <% if can? :read, Audio %>
        <li class="<%= 'active' if current_page?(admin_audios_path) %>"><a href="<%= admin_audios_path %>"><i class='fa fa-music'></i> <span>Audios</span></a></li>
      <% end %>
      <% if can? :read, Activity %>
        <li class="<%= 'active' if current_page?(admin_activities_path) %>"><a href="<%= admin_activities_path %>"><i class='fa fa-th-list'></i> <span>Activities</span></a></li>
      <% end %>
      <% if can? :read, Transaction %>
        <li class="<%= 'active' if current_page?(admin_transactions_path) %>"><a href="<%= admin_transactions_path %>"><i class='fa fa-money'></i> <span>Transactions</span></a></li>
      <% end %>
      <% if can? :read, Setting %>
        <li class="<%= 'active' if current_page?(admin_settings_path) %>"><a href="<%= admin_settings_path %>"><i class='fa fa-cogs'></i> <span>Settings</span></a></li>
      <% end %>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title><%= yield :title %> | <%= Setting.app_name %></title>
  <%= Gon::Base.render_data %>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'admin/application', media: 'all' %>
  <%= javascript_include_tag 'admin/application' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          <%= yield :title %>
        </h1>
      </section>

      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2016 <a href="<%= root_path %>" target="_blank"><%= Setting.app_name %></a>.</strong> All rights reserved.
    </footer>


      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>

  </div><!-- ./wrapper -->
</body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title><%= Setting.app_name %></title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'admin/application', media: 'all' %>
  <%= javascript_include_tag 'admin/application' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
  <% if notice %>
    <div class="alert alert-success alert-dismissable">
      <i class="fa fa-check"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <b><%= notice %></b>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger alert-dismissable">
      <i class="fa fa-ban"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <b><%= alert %></b>
    </div>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Setting.app_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>